defaults: &defaults
  validation:
    invalid_character_mask: 〓
  admin_display_page_number:
    photo_per_page: 5
    tag_per_page: 5
    event_per_page: 10
    group_per_page: 10
    performer_per_page: 25
    recommend_per_page: 5

  gender:
    male:
      id: 1
      name: "男性"
    female:
      id: 2
      name: "女性"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults